//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.23 at 12:57:07 PM IDT 
//


package com.exlibrisgroup.almarestmodels.representationfiles;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.exlibrisgroup.almarestmodels.representationfiles package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RepresentationFiles_QNAME = new QName("", "representation_files");
    private final static QName _RepresentationFile_QNAME = new QName("", "representation_file");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.exlibrisgroup.almarestmodels.representationfiles
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RepresentationFiles }
     * 
     */
    public RepresentationFiles createRepresentationFiles() {
        return new RepresentationFiles();
    }

    /**
     * Create an instance of {@link RepresentationFile }
     * 
     */
    public RepresentationFile createRepresentationFile() {
        return new RepresentationFile();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RepresentationFiles }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "representation_files")
    public JAXBElement<RepresentationFiles> createRepresentationFiles(RepresentationFiles value) {
        return new JAXBElement<RepresentationFiles>(_RepresentationFiles_QNAME, RepresentationFiles.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RepresentationFile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "representation_file")
    public JAXBElement<RepresentationFile> createRepresentationFile(RepresentationFile value) {
        return new JAXBElement<RepresentationFile>(_RepresentationFile_QNAME, RepresentationFile.class, null, value);
    }

}
